### ISSUE TITLE
Control with one button

### ISSUE THREAD

**Issue by Antikillerbm** [eg321/esp32-motorized-roller-blinds#15]
Add this option to the main project if you want
https://github.com/Antikillerbm/esp32-motorized-roller-blinds

**Comment by eg321** [comment]
Hi,
Your changes currently remove possibility to control blinds with up/down switch.
I'll gladly accept your changes once you'll implement them as separate option, not removing current options.

Thanks.

**Comment by Antikillerbm** [comment]
Now you can select by defining the parameter

**Comment by eg321** [comment]
Can you create pull request from your fork please? 
It's better to discuss changes there.
