### ISSUE TITLE
Different Stepper Motor

### ISSUE THREAD

**Issue by KaeShoru** [eg321/esp32-motorized-roller-blinds#17]
Hello. I tried to make a curtain with the motor that is written in the article, but it turned out to be too weak for my curtain. I have tried both 5 volt and 12 volt versions. I also changed power supplies, however The roller blind only went down but didn't go up. Hence the question: is it possible to connect a nema17 instead of28BYJ-48. And how to do it?

**Comment by eg321** [comment]
Hi!
Are you sure that wirings is correct? If you switch one of phase line on motor, torque will decrease drastically.
Also, check your ULN2003 driver. All 4 leds should blink on the move during correct work.

I'm using several blinds with 28BYJ-48 12v each day for couple years. They are not fast, but always open\close my blinds correctly without any issues. 

About nema12 - yes, most probably it can be integrated without huge issues. Main issue: "CheapStepper" library (that used currently) does not support nema17 motors and drivers. It should be switched to some another library.

If you'll adapt codebase for Nema17, please tell me. I'll try to assist you to easily integrate your changes into upstream branch.

**Comment by KaeShoru** [comment]
Yes, I connected everything correctly, as far as I can tell. I also registered connections as "5,4,0,2" as written earlier. The motor rotates in both directions, but it seems to lack torque. Perhaps I need to remove the jumper on the power circuit 5v on ULN2003? To be honest, I have never done anything like this before, so I may not understand something.

**Comment by RobertRupa** [comment]
Check connections between stepper motor and ULN2003. Connecting nema motors should b no problem if max rating of driver and power supply are not exceed.

**Comment by KaeShoru** [comment]
The connection between the motor and the controller is implemented through connectors, there is nothing to confuse here. During this time, I tried motors from different places and different power supplies, but the torque is still not enough.The motor just broke after several attempts to raise the shade. As I understand it, it is simply too heavy for this motor (1,4 length and blackout material).

**Comment by eg321** [comment]
It looks as some HW issue for me. Closing this issue. Please create another one, if you think I'm wrong.
