### ISSUE TITLE
Control via MQTT

### ISSUE THREAD

**Issue by DennisRoschke** [eg321/esp32-motorized-roller-blinds#26]
Hey, unfortunately I don't understand which commands can be sent via MQTT to enable an action.
for example to lower the blinds.

**Comment by eg321** [comment]
Hi,
unfortunately it's not documented well, but actually it's simple. Just 2 things to know:
1. What topics are used described here: https://github.com/eg321/esp32-motorized-roller-blinds#mqtt
2. How to pack your data you can see at WebUI in Websocket channel (MQTT uses same messages):
![image](https://user-images.githubusercontent.com/10514429/233552018-8f9821e4-e24e-4f1c-a023-5dbaab31fe27.png)
So, to move your blinds lower you can send something like this:
```json
{num: 1, action: "auto", value: 100}
```
this means: stepper №1 should automatically move blinds into 100% position (fully closed).
It's a main scenario, but another commands (f. e. to calibrate your blinds or stop movement) you can find here: https://github.com/eg321/esp32-motorized-roller-blinds/blob/master/src/main.cpp#L135

**Comment by DennisRoschke** [comment]
Thanks it Works
