### ISSUE TITLE
Motor issues.

### ISSUE THREAD

**Issue by ZlobidloCZ** [eg321/esp32-motorized-roller-blinds#29]
Hi, I uploaded to the D1 mini USB C version and am having issues with the motor not spinning and not turning off the coils, which is draining power. Has anyone encountered this issue?

**Comment by eg321** [comment]
Hi!
You've configured GPIO incorrectly most probably.
Can you describe/show your setup?

**Comment by ZlobidloCZ** [comment]
I could not find any configuration in the code, and I tried every combination of D1-4 with INTs. In the web config, I set 1,2,3,4 as I use D1-4 for the board. It works without any issue on the previous software on which yours is built. So is there a way to configure D1 mini in firmware?

**Comment by eg321** [comment]
Pins should be configured at Captive portal: https://github.com/eg321/esp32-motorized-roller-blinds?tab=readme-ov-file#captive-portal

Did you tried this?

**Comment by ZlobidloCZ** [comment]
Yes I did this configuration, I placed 1,2,3,4 in motor 1 because I have only one motor hooked up. And I got just Humm from the motor and also the coils did not turn off the whole time.

**Comment by eg321** [comment]
Did you checked that these pins are really 1,2,3,4 ? Please share photo where we can see pins and connections.

**Comment by ZlobidloCZ** [comment]
![PXL_20241113_142901157](https://github.com/user-attachments/assets/e41d32ca-24d3-4e50-8dbe-0cf86c2dbff5)
Here is the picture, D1 is INT1, and so on.

**Comment by eg321** [comment]
According to pic below, correct pin numbers are 5, 4, 0 and 2:
![image](https://github.com/user-attachments/assets/05bee3cd-d293-4621-91a5-02e208ea6fba)

You need to reset and correct pin numbers.

**Comment by ZlobidloCZ** [comment]
I identified the pins corresponding to the picture, and it worked! Thank you so much for explaining this issue to me. Additionally, if I were to implement buttons, would they simply be connected to another GPIO and ground, allowing them to control all motors at once? Or do they function differently?

**Comment by eg321** [comment]
You're welcome.
Yes, buttons will control all motors at once. It will be triggered by high-level (3.3v for esp8266) as I remember.
