### ISSUE TITLE
General - Installation

### ISSUE THREAD

**Issue by phillipmj** [eg321/esp32-motorized-roller-blinds#3]
Hi, 

I'am to this esp8266 programing, I do have a question how to get to compile right, are getting some errors when I open the project in VS. are there a list of dependencies needed to be installed along ?

Best regards
Phillip

**Comment by eg321** [comment]
Hi!
All dependencies should be resolved with Platformio (platformio.ini).

Can you provide details for your errors?

Thanks.

**Comment by phillipmj** [comment]
Hi, 

This are the errors i got

best regadrs
Phillip

I downloaded the file via your "release tap".

Executing task in folder esp32-motorized-roller-blinds-1.4.2: C:\Users\Hiro\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing esp32 (platform: espressif32; board: esp32dev; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (3.3.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - tool-mkspiffs 2.230.0 (2.30)
 - tool-openocd-esp32 2.1000.20210401 (10.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 31 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP-WiFiSettings> 3.8.0
|   |-- <DNSServer> 1.1.0
|   |   |-- <WiFi> 1.0
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <WebServer> 1.0
|   |   |-- <WiFi> 1.0
|   |   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <CheapStepper> 0.2.1
|-- <ArduinoJson> 5.13.4
|-- <FS> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <WebServer> 1.0
|   |-- <WiFi> 1.0
|   |-- <FS> 1.0
|-- <WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <Update> 1.0
|   |-- <WiFi> 1.0
|   |-- <ESPmDNS> 1.0
|   |   |-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\esp32\src\NidayandHelper.cpp.o
Compiling .pio\build\esp32\src\main.cpp.o
Generating partitions .pio\build\esp32\partitions.bin
Compiling .pio\build\esp32\lib216\WiFi\ETH.cpp.o
Compiling .pio\build\esp32\lib216\WiFi\WiFi.cpp.o
Compiling .pio\build\esp32\lib216\WiFi\WiFiAP.cpp.o
Compiling .pio\build\esp32\lib216\WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp32\lib216\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\esp32\lib216\WiFi\WiFiMulti.cpp.o
src\main.cpp:15:30: fatal error: WebSocketsServer.h: No such file or directory

**************************************************************************
* Looking for WebSocketsServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WebSocketsServer.h"
* Web  > https://platformio.org/lib/search?query=header:WebSocketsServer.h
*
**************************************************************************

compilation terminated.
*** [.pio\build\esp32\src\main.cpp.o] Error 1
In file included from src\NidayandHelper.cpp:2:0:
src\NidayandHelper.h:9:26: fatal error: PubSubClient.h: No such file or directory

**********************************************************************
* Looking for PubSubClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:PubSubClient.h"
* Web  > https://platformio.org/lib/search?query=header:PubSubClient.h
*
**********************************************************************

compilation terminated.
*** [.pio\build\esp32\src\NidayandHelper.cpp.o] Error 1
========================================================================== [FAILED] Took 5.93 seconds ==========================================================================

Environment    Status    Duration
-------------  --------  ------------
esp32          FAILED    00:00:05.927
===================================================================== 1 failed, 0 succeeded in 00:00:05.927 =====================================================================The terminal process "C:\Users\Hiro\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by eg321** [comment]
Several dependencies were missed in platformio.ini. It's already fixed in upcoming release 2.0.
You can try it from "master". It's quite stable, but not documented well yet. It includes bunch of fixes and improvements. For example almost all configurations moved to WiFi captive portal (including steppers, pins, speed, etc).

Or you can apply changes from that commit: https://github.com/eg321/esp32-motorized-roller-blinds/commit/f1adf61c16b4bdfcb7aebb582e5a5676e357bd94

**Comment by eg321** [comment]
2.0 is released today: https://github.com/eg321/esp32-motorized-roller-blinds/releases/tag/v2.0

Closing the issue. Feel free to reopen if still actually.
