### ISSUE TITLE
v2 boot loop

### ISSUE THREAD

**Issue by nikkisstuff** [eg321/esp32-motorized-roller-blinds#6]
Ive built and flashed v2 esp8266 version but it is stuck in a boot loop. This is the output from the esp exception decoder

Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
PC: 0x40220284
EXCVADDR: 0x0003aaaa

Decoding stack results

**Comment by eg321** [comment]
Hi!
Have you erased it before flashing? Most probably old config conflicts with new codebase.

I have one esp8266 working fine with v2.

**Comment by nikkisstuff** [comment]
I have erased the board and i still have the same problem. I then tried am 2nd board and its just the same. This is the output from the build.
> Executing task: C:\Users\nikki\.platformio\penv\Scripts\platformio.exe run --environment esp12e <

Processing esp12e (platform: espressif8266; board: nodemcuv2; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (3.1.0) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.30001.210627 (3.0.1)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-xtensa 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP-WiFiSettings> 3.8.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <LittleFS> 0.1.0
|-- <CheapStepper> 0.2.1
|-- <ArduinoJson> 5.13.4
|-- <Button2> 1.6.2
|-- <WebSockets> 2.3.6
|   |-- <ESP8266WiFi> 1.0
|   |-- <Ethernet> 2.0.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <PubSubClient> 2.8.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <LittleFS> 0.1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
Building in release mode
Compiling .pio\build\esp12e\src\Helpers\ButtonsHelper.cpp.o
Compiling .pio\build\esp12e\src\Helpers\ConfigHelper.cpp.o
Compiling .pio\build\esp12e\src\Helpers\MqttHelper.cpp.o
Compiling .pio\build\esp12e\src\Helpers\StepperHelper.cpp.o
Compiling .pio\build\esp12e\src\main.cpp.o
Generating LD script .pio\build\esp12e\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFi.cpp.o
src\main.cpp: In function 'void webSocketEvent(uint8_t, WStype_t, uint8_t*, size_t)':
src\main.cpp:213:12: warning: enumeration value 'WStype_ERROR' not handled in switch [-Wswitch]
  213 |     switch (type) {
      |            ^
src\main.cpp:213:12: warning: enumeration value 'WStype_BIN' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_FRAGMENT_TEXT_START' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_FRAGMENT_BIN_START' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_FRAGMENT' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_FRAGMENT_FIN' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_PING' not handled in switch [-Wswitch]
src\main.cpp:213:12: warning: enumeration value 'WStype_PONG' not handled in switch [-Wswitch]
src\main.cpp: In function 'void mqttCallback(char*, byte*, unsigned int)':
src\main.cpp:233:24: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiAP.cpp.o
  233 |     for (auto i = 0; i < length; i++) {
      |                      ~~^~~~~~~~
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\esp12e\libbdf\ESP8266WiFi\enable_wifi_at_boot_time.cpp.o
Compiling .pio\build\esp12e\lib5ef\DNSServer\DNSServer.cpp.o
Compiling .pio\build\esp12e\lib1d3\ESP8266WebServer\detail\mimetable.cpp.o
Archiving .pio\build\esp12e\lib1d3\libESP8266WebServer.a
Compiling .pio\build\esp12e\libbbf\LittleFS\LittleFS.cpp.o
Compiling .pio\build\esp12e\libbbf\LittleFS\lfs.c.o
Archiving .pio\build\esp12e\libbdf\libESP8266WiFi.a
Compiling .pio\build\esp12e\libbbf\LittleFS\lfs_util.c.o
Archiving .pio\build\esp12e\lib5ef\libDNSServer.a
Compiling .pio\build\esp12e\libe9b\ESP-WiFiSettings\WiFiSettings.cpp.o
Compiling .pio\build\esp12e\lib9b0\CheapStepper\CheapStepper.cpp.o
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp: In constructor 'CheapStepper::CheapStepper()':
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp:29:49: warning: list-initializer for non-class type must not be parenthesized
   29 | CheapStepper::CheapStepper () : pins({8,9,10,11}) {
      |                                                 ^
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp: In constructor 'CheapStepper::CheapStepper(int, int, int, int)':
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp:35:89: warning: list-initializer for non-class type must not be parenthesized
   35 | CheapStepper::CheapStepper (int in1, int in2, int in3, int in4) : pins({in1,in2,in3,in4}) {
      |                                                                                         ^
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp: In member function 'void CheapStepper::run()':
.pio\libdeps\esp12e\CheapStepper\CheapStepper.cpp:137:30: warning: comparison of integer expressions of different signedness: 'long unsigned int' and 'int' [-Wsign-compare]
  137 |  if (micros() - lastStepTime >= delay) { // if time for step
      |      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
Archiving .pio\build\esp12e\libfa5\libArduinoJson.a
Archiving .pio\build\esp12e\libbbf\libLittleFS.a
Compiling .pio\build\esp12e\lib1bd\Button2\Button2.cpp.o
Compiling .pio\build\esp12e\libd93\SPI\SPI.cpp.o
Archiving .pio\build\esp12e\lib9b0\libCheapStepper.a
Compiling .pio\build\esp12e\libf4d\Ethernet\Dhcp.cpp.o
Archiving .pio\build\esp12e\lib1bd\libButton2.a
Compiling .pio\build\esp12e\libf4d\Ethernet\Dns.cpp.o
Archiving .pio\build\esp12e\libd93\libSPI.a
Compiling .pio\build\esp12e\libf4d\Ethernet\Ethernet.cpp.o
Compiling .pio\build\esp12e\libf4d\Ethernet\EthernetClient.cpp.o
Compiling .pio\build\esp12e\libf4d\Ethernet\EthernetServer.cpp.o
Archiving .pio\build\esp12e\libe9b\libESP-WiFiSettings.a
Compiling .pio\build\esp12e\libf4d\Ethernet\EthernetUdp.cpp.o
Compiling .pio\build\esp12e\libf4d\Ethernet\socket.cpp.o
Compiling .pio\build\esp12e\libf4d\Ethernet\utility\w5100.cpp.o
Compiling .pio\build\esp12e\lib2fb\Hash\Hash.cpp.o
Compiling .pio\build\esp12e\libe65\WebSockets\SocketIOclient.cpp.o
Compiling .pio\build\esp12e\libe65\WebSockets\WebSockets.cpp.o
Archiving .pio\build\esp12e\libf4d\libEthernet.a
Compiling .pio\build\esp12e\libe65\WebSockets\WebSocketsClient.cpp.o
Archiving .pio\build\esp12e\lib2fb\libHash.a
Compiling .pio\build\esp12e\libe65\WebSockets\WebSocketsServer.cpp.o
Compiling .pio\build\esp12e\libe65\WebSockets\libb64\cdecode.c.o
Compiling .pio\build\esp12e\libe65\WebSockets\libb64\cencode.c.o
Compiling .pio\build\esp12e\libe65\WebSockets\libsha1\libsha1.c.o
Compiling .pio\build\esp12e\lib9b0\PubSubClient\PubSubClient.cpp.o
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\ESP8266mDNS.cpp.o
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\LEAmDNS.cpp.o
Archiving .pio\build\esp12e\libe65\libWebSockets.a
.pio\libdeps\esp12e\PubSubClient\src\PubSubClient.cpp: In member function 'boolean PubSubClient::publish_P(const char*, const uint8_t*, unsigned int, boolean)':
.pio\libdeps\esp12e\PubSubClient\src\PubSubClient.cpp:523:16: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  523 |     return (rc == expectedLength);
      |             ~~~^~~~~~~~~~~~~~~~~
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\LEAmDNS_Control.cpp.o
Archiving .pio\build\esp12e\lib9b0\libPubSubClient.a
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\LEAmDNS_Helpers.cpp.o
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\LEAmDNS_Structs.cpp.o
Compiling .pio\build\esp12e\lib4db\ESP8266mDNS\LEAmDNS_Transfer.cpp.o
Compiling .pio\build\esp12e\lib354\ArduinoOTA\ArduinoOTA.cpp.o
Archiving .pio\build\esp12e\libFrameworkArduinoVariant.a
Compiling .pio\build\esp12e\FrameworkArduino\Crypto.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Esp-frag.cpp.o
Archiving .pio\build\esp12e\lib4db\libESP8266mDNS.a
Compiling .pio\build\esp12e\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\FS.cpp.o
Archiving .pio\build\esp12e\lib354\libArduinoOTA.a
Compiling .pio\build\esp12e\FrameworkArduino\FSnoop.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\LwipDhcpServer-NonOS.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\LwipDhcpServer.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\LwipIntf.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\LwipIntfCB.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Print.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Schedule.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\StreamSend.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\TypeConversion.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\Updater.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\WString.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\abi.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\aes_unwrap.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\base64.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\cont.S.o
Compiling .pio\build\esp12e\FrameworkArduino\cont_util.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_eboot_command.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_features.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_flash_quirks.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_flash_utils.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_i2s.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_main.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_non32xfer.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_noniso.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_phy.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_postmortem.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_si2c.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_sigma_delta.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_spi_utils.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_timer.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_vm.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_waveform_phase.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_waveform_pwm.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring_analog.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring_digital.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring_pulse.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring_pwm.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\core_esp8266_wiring_shift.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\crc32.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\debug.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\exc-c-wrapper-handler.S.o
Compiling .pio\build\esp12e\FrameworkArduino\exc-sethandler.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\flash_hal.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\gdb_hooks.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\heap.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\hwdt_app_entry.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\libc_replacements.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\mmu_iram.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\reboot_uart_dwnld.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs\spiffs_cache.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs\spiffs_check.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs\spiffs_gc.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs\spiffs_hydrogen.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs\spiffs_nucleus.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\spiffs_api.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\sqrt32.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\stdlib_noniso.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\time.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\uart.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\umm_malloc\umm_info.c.o
Compiling .pio\build\esp12e\FrameworkArduino\umm_malloc\umm_integrity.c.o
Compiling .pio\build\esp12e\FrameworkArduino\umm_malloc\umm_local.c.o
Compiling .pio\build\esp12e\FrameworkArduino\umm_malloc\umm_malloc.cpp.o
Compiling .pio\build\esp12e\FrameworkArduino\umm_malloc\umm_poison.c.o
Archiving .pio\build\esp12e\libFrameworkArduino.a
Linking .pio\build\esp12e\firmware.elf
Retrieving maximum program size .pio\build\esp12e\firmware.elf
Checking size .pio\build\esp12e\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [======    ]  56.5% (used 46260 bytes from 81920 bytes)
Flash: [====      ]  40.5% (used 422852 bytes from 1044464 bytes)
Building .pio\build\esp12e\firmware.bin
Creating BIN file ".pio\build\esp12e\firmware.bin" using "C:\Users\nikki\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" and ".pio\build\esp12e\firmware.elf"
================================================================== [SUCCESS] Took 75.61 seconds ==================================================================
Environment    Status    Duration
-------------  --------  ------------
esp12e         SUCCESS   00:01:15.614
================================================================== 1 succeeded in 00:01:15.614 ================================================================== 

Terminal will be reused by tasks, press any key to close it.

**Comment by eg321** [comment]
Can you enable esp8266_exception_decoder and provide stacktrace here please? It can help to find rootcause.

https://docs.platformio.org/en/latest//core/userguide/device/cmd_monitor.html#cmd-device-monitor-filters

it can be enabled at "monitor_filters" in platformio.ini.

Also, what board do you use? As I can see: `HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash`
But uploader shows "1044464 bytes" at your flash. It looks strange.

**Comment by nikkisstuff** [comment]
Yes I am using "HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash" am using this to get the output. I have done a fresh flash of v1.4.2 and it is working perfectly 

[env:log_output_to_file]
platform = espressif8266
board = nodemcuv2
monitor_filters = esp8266_exception_decoder

here is the log output
https://drive.google.com/drive/folders/1ejygLXW3mg4O0sA7DSVw5WjxLC8ueBJE?usp=sharing

**Comment by nikkisstuff** [comment]
I've just tried on a 3rd board new out of the packet and i get the same error

**Comment by nikkisstuff** [comment]
I have rolled back to V1.4.2. and everything is working fine again
